# Configurações de API
BINANCE_API_KEY = "YOUR_BINANCE_API_KEY"
BINANCE_SECRET_KEY = "YOUR_BINANCE_SECRET_KEY"

GLASSNODE_API_KEY = "YOUR_GLASSNODE_API_KEY"

CRYPTOPANIC_API_KEY = "YOUR_CRYPTOPANIC_API_KEY"

TWITTER_CONSUMER_KEY = "TWITTER_CONSUMER_KEY"
TWITTER_CONSUMER_SECRET = "TWITTER_CONSUMER_SECRET"
TWITTER_ACCESS_TOKEN = "TWITTER_ACCESS_TOKEN"
TWITTER_ACCESS_TOKEN_SECRET = "TWITTER_ACCESS_TOKEN_SECRET"

# Configurações do sistema
SYMBOL = "BTC/USDT"
TIMEFRAME = "5m"
BUY_THRESHOLD = 90
SELL_THRESHOLD = 40
ANALYSIS_INTERVAL = 600  # segundos
